name: Test Reusable Workflow

on:
  push:
    branches:
      - master

jobs:
  test_reusable_workflow:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      image-name: tuansondocker1407/test-azure
      registry: docker.io
      dockerfile-path: ./Dockerfile
      context: .
