name: Test Reusable Workflow

on:
  push:
    branches:
      - master
permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write

jobs:
  docker-back-end:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      image-name: tuansondocker1407/test-azure
      registry: docker.io
      dockerfile-path: ./backend/Dockerfile
      context: ./backend
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  docker-front-end:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      image-name: tuansondocker1407/test-azure
      registry: docker.io
      dockerfile-path: ./frontend/Dockerfile
      context: ./frontend
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
