name: Unit Tests

on:
  workflow_call:
    inputs:
      react_project_dir:
        required: true
        type: string
      dotnet_project_dir:
        required: true
        type: string

jobs:
  react-unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd ${{ inputs.react_project_dir }}
    - run: tree
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test


  dotnet-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore and Run .NET Unit Tests
        run: |
          cd ${{ inputs.dotnet_project_dir }}
          dotnet restore
          dotnet test --no-build --verbosity normal
