name: Unit Tests

on:
  workflow_call:
    inputs:
      react_project_dir:
        required: true
        type: string
      dotnet_project_dir:
        required: true
        type: string

jobs:
  react-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Install Dependencies and Run React Unit Tests
        run: |
          cd ${{ inputs.react_project_dir }}
          npm ci
          npm test

  dotnet-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore and Run .NET Unit Tests
        run: |
          cd ${{ inputs.dotnet_project_dir }}
          dotnet restore
          dotnet test --no-build --verbosity normal
