name: Unit Tests Reusable Workflow

on:
  workflow_call:
    inputs:
      react_project_dir:
        required: true
        type: string
      dotnet_project_dir:
        required: true
        type: string

jobs:
  react-unit-tests:
    continue-on-error: 
      true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'   
        cache-dependency-path: './frontend/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test


  dotnet-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore and Run .NET Unit Tests
        run: |
          cd ${{ inputs.dotnet_project_dir }}
          dotnet restore
          dotnet test --no-build --verbosity normal
